// Seed dataset for DishGenie: ~50 classic Indian / Indian-style recipes.
//
// This file is pure data. It is consumed by scripts/seedRecipes.js which:
//   - connects to the existing MongoDB database,
//   - validates every recipe through the existing Recipe Mongoose model,
//   - skips recipes whose slug already exists (idempotent),
//   - inserts only brand-new recipes, and
//   - never deletes, overwrites or resets any existing documents.
//
// Nutrition values are approximate per-serving estimates (estimated: true,
// perServing: true) and are NOT medically verified data.
//
// Thumbnail URLs point to stable Wikimedia Commons / TheMealDB images that
// match each dish and were individually checked (HTTP 200). Where no matching,
// verifiable image could be found the thumbnail is intentionally left empty.

module.exports = [
  {
    name: "Paneer Butter Masala",
    slug: "paneer-butter-masala",
    area: "Indian",
    isVeg: true,
    category: "Paneer",
    tags: ["indian", "paneer", "vegetarian", "dinner", "creamy", "high-protein"],
    ingredients: [
      { name: "paneer", quantity: "250 g" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "tomato puree", quantity: "300 ml" },
      { name: "onion", quantity: "1 large" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "cashews", quantity: "20 g" },
      { name: "cream", quantity: "100 ml" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "kashmiri red chilli powder", quantity: "1 tsp" },
      { name: "sugar", quantity: "1 tsp" },
      { name: "kasuri methi", quantity: "1 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the cashews in warm water for 15 minutes, then blend with 2 tbsp of water into a smooth paste.",
      "Melt 1 tbsp of butter in a pan and fry the paneer cubes until light golden on the edges. Remove and set aside.",
      "In the same pan add the remaining butter and saute the onion until soft and translucent.",
      "Add the ginger garlic paste and cook for a minute until fragrant, then stir in the tomato puree.",
      "Add the kashmiri red chilli powder, sugar and salt, and simmer for 8-10 minutes until the puree thickens and the oil separates.",
      "Add the cashew paste and 100 ml water, cook for 3-4 minutes, then stir in the cream and garam masala.",
      "Crush the kasuri methi between your palms into the gravy, add the fried paneer and simmer for 3 minutes. Serve hot with naan or jeera rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/4/49/Paneer_Butter_Masala_-_Garnished.jpg",
    youtube: "https://www.youtube.com/watch?v=bUounn_Bmy4",
    sourceUrl: "",
    nutrition: { calories: 520, protein: 22, carbohydrates: 18, fat: 40, fiber: 3, sugar: 7, sodium: 700, estimated: true, perServing: true },
    cookingTime: 35,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Shahi Paneer",
    slug: "shahi-paneer",
    area: "Indian",
    isVeg: true,
    category: "Paneer",
    tags: ["indian", "paneer", "vegetarian", "dinner", "creamy", "rich"],
    ingredients: [
      { name: "paneer", quantity: "250 g" },
      { name: "onion", quantity: "2 medium" },
      { name: "tomato", quantity: "3 medium" },
      { name: "cashews", quantity: "25 g" },
      { name: "almonds", quantity: "15 g" },
      { name: "cream", quantity: "100 ml" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "green cardamom", quantity: "3 pods" },
      { name: "saffron", quantity: "a pinch" },
      { name: "sugar", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the cashews and almonds in warm water for 20 minutes, then grind into a fine paste with a little water.",
      "Warm the saffron strands in 2 tbsp of warm milk and keep aside.",
      "Heat the ghee and saute the green cardamom pods for a few seconds, then add the chopped onions and cook until golden.",
      "Add the chopped tomatoes and cook until soft and mushy, then cool and blend into a smooth puree.",
      "Return the puree to the pan, add the nut paste, sugar and salt, and simmer for 6-8 minutes until well blended.",
      "Stir in the cream, saffron milk and garam masala, then add the paneer cubes.",
      "Simmer gently for 4-5 minutes without boiling hard. Serve with butter naan or jeera rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/5/58/Shahi_Paneer_%26_Butter_Naan.jpg",
    youtube: "https://www.youtube.com/watch?v=WZMOBqbAnbg",
    sourceUrl: "",
    nutrition: { calories: 550, protein: 22, carbohydrates: 20, fat: 42, fiber: 4, sugar: 8, sodium: 680, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Kadai Paneer",
    slug: "kadai-paneer",
    area: "Indian",
    isVeg: true,
    category: "Paneer",
    tags: ["indian", "paneer", "vegetarian", "dinner", "spicy", "high-protein"],
    ingredients: [
      { name: "paneer", quantity: "300 g" },
      { name: "bell pepper", quantity: "1 medium" },
      { name: "onion", quantity: "1 large" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "coriander seeds", quantity: "2 tsp" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "dry red chilli", quantity: "3 whole" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "cream", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Dry roast the coriander seeds, cumin and dry red chillies, then grind them into a coarse kadai masala powder.",
      "Heat oil in a kadai and saute the onion until golden, then add the ginger garlic paste and cook for a minute.",
      "Add the chopped tomatoes and turmeric, and cook until the tomatoes break down into a soft masala.",
      "Sprinkle in the freshly ground kadai masala and cook for 2 minutes, adding a splash of water to keep it moist.",
      "Add the cubed bell pepper and cook for 3 minutes, keeping them slightly crunchy.",
      "Add the paneer cubes, garam masala and salt, and toss gently for 3-4 minutes.",
      "Finish with a swirl of cream and serve hot with tandoori roti or paratha."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Kadai_Paneer_the_Indian_recipe.jpg/960px-Kadai_Paneer_the_Indian_recipe.jpg",
    youtube: "https://www.youtube.com/watch?v=gBnHovVnNwo",
    sourceUrl: "",
    nutrition: { calories: 420, protein: 18, carbohydrates: 16, fat: 32, fiber: 5, sugar: 6, sodium: 650, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Palak Paneer",
    slug: "palak-paneer",
    area: "Indian",
    isVeg: true,
    category: "Paneer",
    tags: ["indian", "paneer", "vegetarian", "dinner", "high-protein", "iron-rich"],
    ingredients: [
      { name: "spinach", quantity: "500 g" },
      { name: "paneer", quantity: "250 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "green chilli", quantity: "2" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "cream", quantity: "2 tbsp" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Blanch the spinach in boiling salted water for 2 minutes, then transfer to iced water.",
      "Blend the blanched spinach with the green chillies and a splash of water into a smooth puree.",
      "Pan-fry the paneer cubes in a little ghee until golden and set aside.",
      "In the same pan, saute the finely chopped garlic, ginger and onion until the onion turns soft and pink.",
      "Add the chopped tomatoes and turmeric and cook until the tomatoes are soft.",
      "Pour in the spinach puree and simmer for 5 minutes, then add the garam masala and salt.",
      "Add the paneer and cream, simmer for 3 minutes and serve hot with roti or rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Palak_Paneer_curry_on_plate.jpg/960px-Palak_Paneer_curry_on_plate.jpg",
    youtube: "https://www.youtube.com/watch?v=Bat8g59fR3g",
    sourceUrl: "",
    nutrition: { calories: 400, protein: 18, carbohydrates: 15, fat: 30, fiber: 5, sugar: 4, sodium: 700, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Chole Masala",
    slug: "chole-masala",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "chickpea", "vegetarian", "dinner", "high-fiber", "high-protein"],
    ingredients: [
      { name: "chickpeas", quantity: "250 g" },
      { name: "onion", quantity: "1 large" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "green chilli", quantity: "2" },
      { name: "chole masala", quantity: "2 tsp" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "tea bag", quantity: "1" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the chickpeas overnight, then pressure-cook them with the tea bag and a little salt until soft. Drain and reserve the cooking liquid.",
      "Heat the oil and crackle the cumin, then saute the onion until golden brown.",
      "Add the ginger garlic paste and green chillies and cook for a minute until fragrant.",
      "Add the chopped tomatoes, turmeric, coriander powder and chole masala, and cook until the oil separates.",
      "Stir in the boiled chickpeas with 1 cup of the reserved cooking liquid.",
      "Simmer uncovered for 15-20 minutes, mashing a few chickpeas against the pan to thicken the gravy.",
      "Adjust salt, garnish with fresh coriander and serve with bhature, kulcha or rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Chole_Bhature_1.jpg/960px-Chole_Bhature_1.jpg",
    youtube: "https://www.youtube.com/watch?v=RXZsDHKlVGw",
    sourceUrl: "",
    nutrition: { calories: 350, protein: 14, carbohydrates: 45, fat: 12, fiber: 12, sugar: 6, sodium: 800, estimated: true, perServing: true },
    cookingTime: 50,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Rajma Masala",
    slug: "rajma-masala",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "rajma", "kidney beans", "vegetarian", "dinner", "high-fiber"],
    ingredients: [
      { name: "kidney beans", quantity: "250 g" },
      { name: "onion", quantity: "1 large" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1 tsp" },
      { name: "green chilli", quantity: "2" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the kidney beans overnight, then pressure-cook with a pinch of salt until soft but whole.",
      "Heat the oil, crackle the cumin, and saute the finely chopped onion until deep golden.",
      "Add the ginger garlic paste and green chillies and cook for a minute.",
      "Add the tomatoes, turmeric, coriander powder and red chilli powder, and cook until the masala turns glossy.",
      "Add the boiled rajma along with its cooking liquid and simmer for 15-20 minutes.",
      "Mash a few beans against the side of the pan to thicken the gravy, then add garam masala and salt.",
      "Serve hot over steamed rice with a dollop of ghee and sliced onion on the side."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rajma_Chawal_Thali.jpg/960px-Rajma_Chawal_Thali.jpg",
    youtube: "https://www.youtube.com/watch?v=d7zEp06mH58",
    sourceUrl: "",
    nutrition: { calories: 320, protein: 15, carbohydrates: 45, fat: 9, fiber: 14, sugar: 5, sodium: 750, estimated: true, perServing: true },
    cookingTime: 55,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Dal Tadka",
    slug: "dal-tadka",
    area: "Indian",
    isVeg: true,
    category: "Dal",
    tags: ["indian", "dal", "lentil", "vegetarian", "lunch", "high-protein"],
    ingredients: [
      { name: "toor dal", quantity: "200 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "garlic", quantity: "6 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "mustard seeds", quantity: "1/2 tsp" },
      { name: "dry red chilli", quantity: "2 whole" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "asafoetida", quantity: "a pinch" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "coriander", quantity: "a handful" }
    ],
    instructions: [
      "Wash the toor dal and pressure-cook it with the turmeric and 3 cups of water until completely soft.",
      "Whisk the cooked dal until smooth, season with salt and thin it with water to a pouring consistency. Simmer for 5 minutes.",
      "Heat the ghee in a small pan for the tadka and crackle the mustard seeds and cumin.",
      "Add the asafoetida, whole dry red chillies and sliced garlic and fry until the garlic turns golden.",
      "Add the chopped onion and tomato, and cook until the tomato softens.",
      "Pour the entire tadka over the simmering dal and mix well.",
      "Garnish with chopped coriander and serve hot with jeera rice or roti."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Tadka_Dal.jpg",
    youtube: "https://www.youtube.com/watch?v=XzVxjs3PTm4",
    sourceUrl: "",
    nutrition: { calories: 280, protein: 14, carbohydrates: 38, fat: 8, fiber: 10, sugar: 4, sodium: 600, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Dal Makhani",
    slug: "dal-makhani",
    area: "Indian",
    isVeg: true,
    category: "Dal",
    tags: ["indian", "dal", "lentil", "vegetarian", "dinner", "creamy", "high-protein"],
    ingredients: [
      { name: "black lentils", quantity: "200 g" },
      { name: "kidney beans", quantity: "50 g" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "cream", quantity: "100 ml" },
      { name: "tomato puree", quantity: "250 ml" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1 tsp" },
      { name: "kasuri methi", quantity: "1 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the black lentils and kidney beans overnight, then pressure-cook until very soft.",
      "Melt the butter in a pan and saute the ginger garlic paste until fragrant.",
      "Add the tomato puree and red chilli powder, and cook until the puree thickens and the oil separates.",
      "Add the cooked dal with its liquid and simmer on a low flame for 25-30 minutes, stirring often.",
      "Stir in the garam masala and kasuri methi and continue simmering.",
      "Blend in the cream and simmer for another 5 minutes.",
      "Serve with naan or rice, topped with a knob of butter."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/DAL_MAKHANI.JPG/960px-DAL_MAKHANI.JPG",
    youtube: "https://www.youtube.com/watch?v=q95YzKQKpIM",
    sourceUrl: "",
    nutrition: { calories: 350, protein: 15, carbohydrates: 35, fat: 16, fiber: 10, sugar: 5, sodium: 700, estimated: true, perServing: true },
    cookingTime: 45,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Aloo Gobi",
    slug: "aloo-gobi",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "potato", "cauliflower", "vegetarian", "dinner", "comfort-food"],
    ingredients: [
      { name: "potato", quantity: "2 medium" },
      { name: "cauliflower", quantity: "1 medium" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1/2 tsp" },
      { name: "ginger", quantity: "1 inch" },
      { name: "garam masala", quantity: "1/2 tsp" },
      { name: "green chilli", quantity: "1" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Cut the potatoes into cubes and the cauliflower into small florets. Wash and drain the florets well.",
      "Heat the oil and crackle the cumin and green chilli.",
      "Add the cubed potatoes and fry for 5 minutes until lightly browned on the edges.",
      "Add the cauliflower florets, turmeric, coriander powder, red chilli powder and salt, and toss well.",
      "Add the grated ginger and cook covered on a low flame for 12-15 minutes, stirring occasionally.",
      "Once the vegetables are tender, remove the lid and dry-roast them for 3-4 minutes to remove excess moisture.",
      "Sprinkle garam masala and fresh coriander, and serve hot with roti."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/34/Aloo_gobi_%283085447892%29.jpg",
    youtube: "https://www.youtube.com/watch?v=8OrZUE1sYEU",
    sourceUrl: "",
    nutrition: { calories: 220, protein: 5, carbohydrates: 30, fat: 9, fiber: 5, sugar: 4, sodium: 550, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Aloo Matar",
    slug: "aloo-matar",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "potato", "peas", "vegetarian", "dinner", "comfort-food"],
    ingredients: [
      { name: "potato", quantity: "3 medium" },
      { name: "green peas", quantity: "150 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1/2 tsp" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the potatoes until just cooked, then peel and cut them into cubes.",
      "Heat the oil, crackle the cumin, and saute the chopped onion until golden.",
      "Add the ginger garlic paste and cook for a minute, then add the chopped tomatoes and turmeric.",
      "Cook the tomatoes until soft, then add the coriander powder, red chilli powder and salt.",
      "Add the potato cubes and green peas with 1/2 cup of water.",
      "Cover and simmer for 10 minutes until the peas are tender and the gravy thickens.",
      "Finish with garam masala and serve hot with rice or chapati."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Aloo_matar_-_Massachusetts.jpg/960px-Aloo_matar_-_Massachusetts.jpg",
    youtube: "https://www.youtube.com/watch?v=oVfWo91JoSM",
    sourceUrl: "",
    nutrition: { calories: 260, protein: 8, carbohydrates: 38, fat: 9, fiber: 7, sugar: 6, sodium: 600, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Bhindi Masala",
    slug: "bhindi-masala",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "okra", "vegetarian", "dinner", "gluten-free"],
    ingredients: [
      { name: "okra", quantity: "400 g" },
      { name: "onion", quantity: "1 large" },
      { name: "tomato", quantity: "2 medium" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "amchur", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1/2 tsp" },
      { name: "ginger", quantity: "1 inch" },
      { name: "oil", quantity: "3 tbsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Wash the okra thoroughly and pat completely dry. Slice into 1 cm rounds.",
      "Heat 2 tbsp of oil in a wide pan and stir-fry the okra on medium heat for 6-8 minutes until the stickiness goes away.",
      "Remove the okra and set aside. Add the remaining oil and crackle the cumin.",
      "Saute the sliced onion until golden, then add the grated ginger and chopped tomatoes.",
      "Add the turmeric, coriander powder, red chilli powder and salt, and cook until the tomatoes soften.",
      "Return the fried okra to the pan, add the amchur, and toss on high heat for 2-3 minutes.",
      "Garnish with coriander and serve hot with roti."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bhindi_Masala.jpg/960px-Bhindi_Masala.jpg",
    youtube: "https://www.youtube.com/watch?v=SYCG7Mn0IWc",
    sourceUrl: "",
    nutrition: { calories: 180, protein: 4, carbohydrates: 16, fat: 11, fiber: 6, sugar: 4, sodium: 500, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Baingan Bharta",
    slug: "baingan-bharta",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "eggplant", "vegetarian", "dinner", "smoky"],
    ingredients: [
      { name: "eggplant", quantity: "1 large" },
      { name: "onion", quantity: "1 large" },
      { name: "tomato", quantity: "2 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "green chilli", quantity: "2" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1/2 tsp" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Prick the eggplant a few times and roast it over an open flame or in a preheated oven at 220C until the skin chars and the flesh is soft.",
      "Cool the eggplant, peel off the charred skin and mash the flesh roughly with a fork.",
      "Heat the oil, crackle the cumin, and saute the chopped onion until golden.",
      "Add the ginger garlic paste and green chillies and cook for a minute.",
      "Add the chopped tomatoes, turmeric, coriander powder and salt, and cook until the tomatoes are soft and pulpy.",
      "Add the mashed eggplant and cook for 8-10 minutes, stirring often.",
      "Finish with garam masala and fresh coriander, and serve with roti or paratha."
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
    youtube: "https://www.youtube.com/watch?v=-84Zz2EP4h4",
    sourceUrl: "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
    nutrition: { calories: 210, protein: 4, carbohydrates: 22, fat: 12, fiber: 6, sugar: 8, sodium: 550, estimated: true, perServing: true },
    cookingTime: 35,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Mixed Vegetable Curry",
    slug: "mixed-vegetable-curry",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "vegetables", "vegetarian", "dinner", "high-fiber", "low-calorie"],
    ingredients: [
      { name: "potato", quantity: "1 medium" },
      { name: "carrot", quantity: "1 medium" },
      { name: "green beans", quantity: "100 g" },
      { name: "cauliflower", quantity: "150 g" },
      { name: "green peas", quantity: "100 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "oil", quantity: "2 tbsp" }
    ],
    instructions: [
      "Cut all the vegetables into small, even pieces and keep the peas separate.",
      "Heat the oil and saute the chopped onion until soft and light golden.",
      "Add the ginger garlic paste and cook for a minute, then add the chopped tomatoes.",
      "Add the turmeric, coriander powder and salt, and cook the tomatoes until they turn soft.",
      "Add the firmer vegetables (potato, carrot, beans) first and cook covered for 5 minutes.",
      "Add the cauliflower and peas with 1/2 cup of water, and simmer covered for 12-15 minutes until tender.",
      "Sprinkle garam masala, cook for 2 more minutes and serve with roti or rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Mixed_vegetable_curry_1.jpg/960px-Mixed_vegetable_curry_1.jpg",
    youtube: "https://www.youtube.com/watch?v=E8YWCFBhDQU",
    sourceUrl: "",
    nutrition: { calories: 230, protein: 6, carbohydrates: 28, fat: 11, fiber: 7, sugar: 6, sodium: 600, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Malai Kofta",
    slug: "malai-kofta",
    area: "Indian",
    isVeg: true,
    category: "Dinner",
    tags: ["indian", "kofta", "paneer", "vegetarian", "dinner", "rich"],
    ingredients: [
      { name: "paneer", quantity: "200 g" },
      { name: "potato", quantity: "2 medium" },
      { name: "cornflour", quantity: "2 tbsp" },
      { name: "tomato", quantity: "3 medium" },
      { name: "cashews", quantity: "30 g" },
      { name: "cream", quantity: "100 ml" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "sugar", quantity: "1 tsp" },
      { name: "green cardamom", quantity: "2 pods" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil and mash the potatoes. Mix with the grated paneer, cornflour, a pinch of salt and knead into a soft dough.",
      "Shape the mixture into small balls and deep-fry them until golden. Drain and set aside.",
      "Soak the cashews in warm water, then blend with the cardamom pods and a little water into a smooth paste.",
      "Melt the butter and saute the ginger garlic paste, then add the chopped tomatoes and cook until soft.",
      "Blend the tomatoes, add them back with the cashew paste, sugar and salt, and simmer for 8 minutes.",
      "Add the cream and garam masala and cook for 2-3 minutes more.",
      "Just before serving, add the koftas to the warm gravy and serve with naan or rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Malai_Kofta_Garnished_and_Ready_to_Eat_India.jpg/960px-Malai_Kofta_Garnished_and_Ready_to_Eat_India.jpg",
    youtube: "https://www.youtube.com/watch?v=Tn1UeCKOACU",
    sourceUrl: "",
    nutrition: { calories: 480, protein: 15, carbohydrates: 30, fat: 34, fiber: 5, sugar: 9, sodium: 750, estimated: true, perServing: true },
    cookingTime: 50,
    difficulty: "hard",
    servings: 4
  },
  {
    name: "Chicken Curry",
    slug: "chicken-curry",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "chicken", "non-vegetarian", "dinner", "high-protein", "spicy"],
    ingredients: [
      { name: "chicken", quantity: "600 g" },
      { name: "onion", quantity: "2 medium" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "2 tbsp" },
      { name: "yogurt", quantity: "2 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "red chilli powder", quantity: "1 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "green chilli", quantity: "2" },
      { name: "oil", quantity: "3 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Marinate the chicken pieces with yogurt, turmeric, half the ginger garlic paste and salt for 30 minutes.",
      "Heat the oil and saute the chopped onions until golden brown.",
      "Add the remaining ginger garlic paste and green chillies, and cook for a minute.",
      "Add the chopped tomatoes, red chilli powder and coriander powder, and cook until the oil separates.",
      "Add the marinated chicken and stir well, cooking it for 5-6 minutes until the pieces turn opaque.",
      "Add 1 cup of warm water, cover and simmer for 20-25 minutes until the chicken is cooked through.",
      "Finish with garam masala and serve hot with rice or roti."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Chicken-masala-Indian-curry-in-olive-oil.jpg/960px-Chicken-masala-Indian-curry-in-olive-oil.jpg",
    youtube: "https://www.youtube.com/watch?v=DwBXXOrNIGc",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 30, carbohydrates: 12, fat: 22, fiber: 3, sugar: 4, sodium: 800, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Butter Chicken",
    slug: "butter-chicken",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "chicken", "non-vegetarian", "dinner", "creamy", "high-protein"],
    ingredients: [
      { name: "chicken", quantity: "600 g" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "cream", quantity: "150 ml" },
      { name: "tomato puree", quantity: "300 ml" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "kashmiri red chilli powder", quantity: "1 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "kasuri methi", quantity: "1 tbsp" },
      { name: "honey", quantity: "1 tsp" },
      { name: "yogurt", quantity: "100 g" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Marinate the chicken with yogurt, half the ginger garlic paste, kashmiri red chilli powder and salt for at least 1 hour.",
      "Grill or pan-sear the marinated chicken until lightly charred. Set aside.",
      "Melt the butter and saute the remaining ginger garlic paste for a minute.",
      "Add the tomato puree, garam masala and honey, and simmer for 10 minutes until the sauce deepens in colour.",
      "Add the cream and crushed kasuri methi, and simmer for 3-4 minutes.",
      "Add the grilled chicken and coat well in the sauce, simmering for 5 minutes.",
      "Serve hot with naan or jeera rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Murgh_Makhani_%28Butter_Chicken%29_2_%288925280003%29.jpg/960px-Murgh_Makhani_%28Butter_Chicken%29_2_%288925280003%29.jpg",
    youtube: "https://www.youtube.com/watch?v=2jT9Z4K7xEk",
    sourceUrl: "",
    nutrition: { calories: 450, protein: 28, carbohydrates: 14, fat: 30, fiber: 2, sugar: 6, sodium: 850, estimated: true, perServing: true },
    cookingTime: 45,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Chicken Tikka Masala",
    slug: "chicken-tikka-masala",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "chicken", "non-vegetarian", "dinner", "high-protein", "spicy"],
    ingredients: [
      { name: "chicken", quantity: "500 g" },
      { name: "yogurt", quantity: "150 g" },
      { name: "lemon juice", quantity: "1 tbsp" },
      { name: "ginger garlic paste", quantity: "2 tbsp" },
      { name: "garam masala", quantity: "1 tbsp" },
      { name: "kashmiri red chilli powder", quantity: "1 tbsp" },
      { name: "tomato puree", quantity: "250 ml" },
      { name: "cream", quantity: "100 ml" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "kasuri methi", quantity: "1 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Cut the chicken into bite-sized chunks and prick them lightly with a fork.",
      "Mix the yogurt, lemon juice, ginger garlic paste, garam masala, kashmiri chilli powder and salt, and marinate the chicken for at least 1 hour.",
      "Thread the chicken onto skewers and grill or oven-roast at 220C for 12-15 minutes until charred at the edges.",
      "Melt the butter in a pan and add the tomato puree and a pinch of salt, simmering for 8-10 minutes.",
      "Add the cream and kasuri methi, and simmer for 3 minutes.",
      "Add the grilled chicken tikka and toss in the sauce for 5 minutes.",
      "Serve hot with naan and a squeeze of lemon."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Chicken_Tikka_Masala_on_White_Plate_with_Spoon.jpg/960px-Chicken_Tikka_Masala_on_White_Plate_with_Spoon.jpg",
    youtube: "https://www.youtube.com/watch?v=cMnTchazaAY",
    sourceUrl: "",
    nutrition: { calories: 420, protein: 32, carbohydrates: 15, fat: 26, fiber: 3, sugar: 7, sodium: 900, estimated: true, perServing: true },
    cookingTime: 50,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Mutton Curry",
    slug: "mutton-curry",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "mutton", "lamb", "non-vegetarian", "dinner", "high-protein"],
    ingredients: [
      { name: "mutton", quantity: "600 g" },
      { name: "onion", quantity: "2 medium" },
      { name: "yogurt", quantity: "3 tbsp" },
      { name: "ginger garlic paste", quantity: "2 tbsp" },
      { name: "tomato", quantity: "2 medium" },
      { name: "bay leaf", quantity: "1" },
      { name: "cinnamon", quantity: "1 inch" },
      { name: "cloves", quantity: "3" },
      { name: "coriander powder", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "oil", quantity: "3 tbsp" }
    ],
    instructions: [
      "Marinate the mutton with yogurt, half the ginger garlic paste and salt for 1 hour.",
      "Heat the oil and fry the bay leaf, cinnamon and cloves for a few seconds.",
      "Add the finely sliced onions and saute on medium heat until deep golden brown.",
      "Add the remaining ginger garlic paste and cook until the raw smell goes away.",
      "Add the chopped tomatoes, coriander powder and turmeric, and cook until the tomatoes are fully soft.",
      "Add the marinated mutton and sear for 8-10 minutes, stirring, until the fat renders.",
      "Add 2 cups of warm water, cover and simmer for 60-75 minutes until the mutton is tender.",
      "Sprinkle garam masala, simmer for 2 minutes and serve hot with rice or naan."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mutton_Curry_3.jpg/960px-Mutton_Curry_3.jpg",
    youtube: "https://www.youtube.com/watch?v=XyCOgOFMLiM",
    sourceUrl: "",
    nutrition: { calories: 450, protein: 28, carbohydrates: 12, fat: 30, fiber: 3, sugar: 4, sodium: 850, estimated: true, perServing: true },
    cookingTime: 75,
    difficulty: "hard",
    servings: 4
  },
  {
    name: "Egg Curry",
    slug: "egg-curry",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "egg", "non-vegetarian", "dinner", "high-protein", "quick"],
    ingredients: [
      { name: "eggs", quantity: "6" },
      { name: "onion", quantity: "2 medium" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "red chilli powder", quantity: "1 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "green chilli", quantity: "1" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Hard-boil the eggs, cool them in water, peel and lightly slit the whites so the masala seeps in.",
      "Heat the oil and saute the chopped onions until golden.",
      "Add the ginger garlic paste and green chilli and cook for a minute.",
      "Add the chopped tomatoes, turmeric, red chilli powder and coriander powder, and cook until the oil separates.",
      "Add 1 cup of water and simmer for 5 minutes to build the gravy.",
      "Add the boiled eggs and simmer for 5-6 minutes, spooning the gravy over the eggs.",
      "Finish with garam masala and coriander, and serve with rice or roti."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Egg_%28Anda%29_Curry.JPG/960px-Egg_%28Anda%29_Curry.JPG",
    youtube: "https://www.youtube.com/watch?v=TlYCJ9wTImg",
    sourceUrl: "",
    nutrition: { calories: 320, protein: 16, carbohydrates: 12, fat: 22, fiber: 3, sugar: 4, sodium: 750, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Fish Curry",
    slug: "fish-curry",
    area: "Indian",
    isVeg: false,
    category: "Dinner",
    tags: ["indian", "fish", "seafood", "non-vegetarian", "dinner", "high-protein", "omega-3"],
    ingredients: [
      { name: "fish", quantity: "500 g" },
      { name: "onion", quantity: "2 medium" },
      { name: "tomato", quantity: "3 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1 tsp" },
      { name: "coriander powder", quantity: "1 tbsp" },
      { name: "tamarind", quantity: "1 tsp" },
      { name: "mustard seeds", quantity: "1/2 tsp" },
      { name: "curry leaves", quantity: "8 leaves" },
      { name: "mustard oil", quantity: "3 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Wash the fish pieces and rub them with 1/2 tsp of turmeric and salt. Let them sit for 10 minutes.",
      "Soak the tamarind in warm water for 10 minutes and extract the pulp.",
      "Heat the mustard oil until smoking, then reduce the heat and crackle the mustard seeds and curry leaves.",
      "Saute the chopped onions until golden, then add the ginger garlic paste.",
      "Add the chopped tomatoes, remaining turmeric, red chilli powder and coriander powder, and cook until soft.",
      "Add 1 cup of water and the tamarind pulp, and bring the gravy to a gentle simmer.",
      "Gently slide in the fish pieces and cook uncovered for 8-10 minutes until the fish is just done. Serve with steamed rice."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Fish_Curry_%28965863650%29.jpg/960px-Fish_Curry_%28965863650%29.jpg",
    youtube: "https://www.youtube.com/watch?v=KEFoA6p1FjY",
    sourceUrl: "",
    nutrition: { calories: 280, protein: 28, carbohydrates: 10, fat: 15, fiber: 2, sugar: 3, sodium: 700, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Chicken Biryani",
    slug: "chicken-biryani",
    area: "Indian",
    isVeg: false,
    category: "Biryani",
    tags: ["indian", "chicken", "biryani", "non-vegetarian", "dinner", "high-protein", "rice"],
    ingredients: [
      { name: "chicken", quantity: "500 g" },
      { name: "basmati rice", quantity: "400 g" },
      { name: "yogurt", quantity: "150 g" },
      { name: "onion", quantity: "2 medium" },
      { name: "ginger garlic paste", quantity: "2 tbsp" },
      { name: "biryani masala", quantity: "1 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "saffron", quantity: "a pinch" },
      { name: "mint leaves", quantity: "a handful" },
      { name: "ghee", quantity: "3 tbsp" },
      { name: "bay leaf", quantity: "1" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Marinate the chicken with yogurt, ginger garlic paste, biryani masala, garam masala and salt for at least 1 hour.",
      "Soak the basmati rice for 30 minutes, then parboil in salted water with a bay leaf until 70% done. Drain.",
      "Fry the sliced onions in ghee until crisp and golden, and set half aside for garnish.",
      "In a heavy pot, layer half the marinated chicken at the bottom.",
      "Top with half the rice, mint leaves and saffron-infused milk, then repeat with the remaining chicken and rice.",
      "Dot the top with the fried onions and remaining ghee.",
      "Seal the pot and cook on a low flame (dum) for 25-30 minutes. Rest for 10 minutes before serving with raita."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Chicken-biryani-recipe.jpg",
    youtube: "https://www.youtube.com/watch?v=EiVoWp5b93s",
    sourceUrl: "",
    nutrition: { calories: 550, protein: 28, carbohydrates: 65, fat: 18, fiber: 3, sugar: 3, sodium: 900, estimated: true, perServing: true },
    cookingTime: 60,
    difficulty: "hard",
    servings: 4
  },
  {
    name: "Vegetable Biryani",
    slug: "vegetable-biryani",
    area: "Indian",
    isVeg: true,
    category: "Biryani",
    tags: ["indian", "biryani", "vegetarian", "rice", "lunch", "high-fiber"],
    ingredients: [
      { name: "basmati rice", quantity: "400 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "green beans", quantity: "100 g" },
      { name: "green peas", quantity: "100 g" },
      { name: "cauliflower", quantity: "150 g" },
      { name: "yogurt", quantity: "100 g" },
      { name: "onion", quantity: "1 large" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "biryani masala", quantity: "1 tbsp" },
      { name: "mint leaves", quantity: "a handful" },
      { name: "saffron", quantity: "a pinch" },
      { name: "ghee", quantity: "2 tbsp" }
    ],
    instructions: [
      "Soak the basmati rice for 30 minutes, then parboil in salted water until 70% done and drain.",
      "Cut the vegetables into small even pieces.",
      "Heat the ghee and fry the sliced onion until golden. Remove half and set aside.",
      "Add the ginger garlic paste and biryani masala to the pan, then add the vegetables and yogurt.",
      "Saute the vegetables for 5-6 minutes, then layer them with the parboiled rice in a heavy pot.",
      "Sprinkle mint leaves and saffron milk between the layers and top with the fried onions.",
      "Seal the pot and cook on low (dum) for 20-25 minutes. Rest and serve with raita."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Mumbai_Biryani_-_Hotel_Ibis%2C_Navi_Mumbai_-_Maharashtra-_004.jpg/960px-Mumbai_Biryani_-_Hotel_Ibis%2C_Navi_Mumbai_-_Maharashtra-_004.jpg",
    youtube: "https://www.youtube.com/watch?v=65ihWG9immA",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 8, carbohydrates: 62, fat: 12, fiber: 6, sugar: 5, sodium: 700, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Paneer Biryani",
    slug: "paneer-biryani",
    area: "Indian",
    isVeg: true,
    category: "Biryani",
    tags: ["indian", "biryani", "paneer", "vegetarian", "dinner", "rice", "high-protein"],
    ingredients: [
      { name: "basmati rice", quantity: "400 g" },
      { name: "paneer", quantity: "300 g" },
      { name: "yogurt", quantity: "120 g" },
      { name: "onion", quantity: "1 large" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "biryani masala", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "mint leaves", quantity: "a handful" },
      { name: "saffron", quantity: "a pinch" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Soak the basmati rice for 30 minutes, then parboil in salted water until 70% done and drain.",
      "Marinate the paneer cubes in yogurt, turmeric, half the biryani masala and salt for 15 minutes.",
      "Heat the ghee and fry the sliced onion until golden. Remove half and set aside.",
      "Add the ginger garlic paste and the remaining biryani masala to the pan, then add the marinated paneer.",
      "Gently cook the paneer for 4-5 minutes until the marinade coats it.",
      "Layer the paneer with the parboiled rice, mint and saffron milk, and top with fried onions.",
      "Seal and cook on low (dum) for 20-25 minutes, then rest for 10 minutes before serving."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Panner_Vegetable_Hyderabad_Biryani.jpg/960px-Panner_Vegetable_Hyderabad_Biryani.jpg",
    youtube: "https://www.youtube.com/watch?v=f0C96ir-1Qs",
    sourceUrl: "",
    nutrition: { calories: 480, protein: 16, carbohydrates: 60, fat: 18, fiber: 4, sugar: 5, sodium: 750, estimated: true, perServing: true },
    cookingTime: 45,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Egg Biryani",
    slug: "egg-biryani",
    area: "Indian",
    isVeg: false,
    category: "Biryani",
    tags: ["indian", "biryani", "egg", "non-vegetarian", "dinner", "rice", "high-protein"],
    ingredients: [
      { name: "basmati rice", quantity: "400 g" },
      { name: "eggs", quantity: "6" },
      { name: "yogurt", quantity: "100 g" },
      { name: "onion", quantity: "1 large" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "biryani masala", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "mint leaves", quantity: "a handful" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "red chilli powder", quantity: "1/2 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Hard-boil the eggs, peel them, and lightly fry them in a little ghee until golden. Set aside.",
      "Soak the basmati rice for 30 minutes, then parboil in salted water until 70% done and drain.",
      "Fry the sliced onion in ghee until golden and crisp. Remove half and set aside.",
      "Add the ginger garlic paste, biryani masala, turmeric and red chilli powder to the pan.",
      "Add the yogurt and 1/2 cup of water and simmer into a thin masala base.",
      "Layer the masala, boiled eggs and parboiled rice with mint leaves in a pot.",
      "Seal and cook on low (dum) for 20-25 minutes, then rest and serve with raita."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Spicy_Egg_Biryani.jpg/960px-Spicy_Egg_Biryani.jpg",
    youtube: "https://www.youtube.com/watch?v=yZavuNBAcB4",
    sourceUrl: "",
    nutrition: { calories: 450, protein: 18, carbohydrates: 60, fat: 15, fiber: 3, sugar: 3, sodium: 800, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Jeera Rice",
    slug: "jeera-rice",
    area: "Indian",
    isVeg: true,
    category: "Rice",
    tags: ["indian", "rice", "cumin", "vegetarian", "side", "quick"],
    ingredients: [
      { name: "basmati rice", quantity: "300 g" },
      { name: "cumin", quantity: "2 tsp" },
      { name: "ghee", quantity: "1 tbsp" },
      { name: "bay leaf", quantity: "1" },
      { name: "cloves", quantity: "2" },
      { name: "water", quantity: "600 ml" },
      { name: "salt", quantity: "to taste" },
      { name: "coriander", quantity: "a handful" }
    ],
    instructions: [
      "Wash the basmati rice in water until it runs clear, then soak for 20 minutes and drain.",
      "Heat the ghee in a heavy pan and add the cumin, bay leaf and cloves.",
      "Sizzle the cumin for 30 seconds until fragrant.",
      "Add the drained rice and toss gently for 2 minutes to coat each grain.",
      "Add the water and salt, and bring to a boil.",
      "Cover and cook on the lowest flame for 12-15 minutes until the water is absorbed.",
      "Fluff the rice gently with a fork, garnish with coriander and serve."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Jeera_Rice_India.jpg/960px-Jeera_Rice_India.jpg",
    youtube: "https://www.youtube.com/watch?v=shq0l7-9408",
    sourceUrl: "",
    nutrition: { calories: 280, protein: 5, carbohydrates: 52, fat: 6, fiber: 2, sugar: 1, sodium: 20, estimated: true, perServing: true },
    cookingTime: 20,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Vegetable Pulao",
    slug: "vegetable-pulao",
    area: "Indian",
    isVeg: true,
    category: "Rice",
    tags: ["indian", "rice", "vegetables", "vegetarian", "lunch", "one-pot"],
    ingredients: [
      { name: "basmati rice", quantity: "350 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "green beans", quantity: "80 g" },
      { name: "green peas", quantity: "80 g" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "onion", quantity: "1 medium" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "bay leaf", quantity: "1" },
      { name: "cinnamon", quantity: "1 inch" },
      { name: "cloves", quantity: "3" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "garam masala", quantity: "1 tsp" }
    ],
    instructions: [
      "Wash and soak the basmati rice for 20 minutes, then drain.",
      "Heat the ghee and fry the bay leaf, cinnamon and cloves for a few seconds.",
      "Add the sliced onion and saute until light golden.",
      "Add the ginger garlic paste and all the chopped vegetables, and saute for 5 minutes.",
      "Add the drained rice and garam masala, and toss gently for 2 minutes.",
      "Add 1.5 cups of water and salt, and bring to a boil.",
      "Cover and cook on low for 12-15 minutes until the rice is fluffy. Serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Vegetable_Pulao_as_served_in_South_India.jpg/960px-Vegetable_Pulao_as_served_in_South_India.jpg",
    youtube: "https://www.youtube.com/watch?v=cE8hI55Q_SU",
    sourceUrl: "",
    nutrition: { calories: 330, protein: 7, carbohydrates: 55, fat: 10, fiber: 5, sugar: 4, sodium: 550, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Masala Maggi",
    slug: "masala-maggi",
    area: "Indian",
    isVeg: true,
    category: "Quick Meal",
    tags: ["indian", "maggi", "noodles", "vegetarian", "quick", "comfort-food"],
    ingredients: [
      { name: "instant noodles", quantity: "2 packets" },
      { name: "onion", quantity: "1 small" },
      { name: "tomato", quantity: "1 medium" },
      { name: "green chilli", quantity: "1" },
      { name: "garlic", quantity: "2 cloves" },
      { name: "butter", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/4 tsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil 1.5 cups of water in a pan.",
      "Melt the butter and saute the chopped garlic, onion and green chilli for 2 minutes.",
      "Add the chopped tomato and turmeric, and cook for 2 minutes until the tomato softens.",
      "Add the water, both noodle cakes and the masala seasoning from the packets.",
      "Cook for 2-3 minutes, stirring, until the noodles soften and absorb the masala.",
      "Adjust salt, garnish with coriander and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Masala_noodles.jpeg/960px-Masala_noodles.jpeg",
    youtube: "https://www.youtube.com/watch?v=i6fcX2J0eXU",
    sourceUrl: "",
    nutrition: { calories: 350, protein: 10, carbohydrates: 52, fat: 11, fiber: 3, sugar: 3, sodium: 1100, estimated: true, perServing: true },
    cookingTime: 10,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Vegetable Maggi",
    slug: "vegetable-maggi",
    area: "Indian",
    isVeg: true,
    category: "Quick Meal",
    tags: ["indian", "maggi", "noodles", "vegetables", "vegetarian", "quick"],
    ingredients: [
      { name: "instant noodles", quantity: "2 packets" },
      { name: "carrot", quantity: "1/2 medium" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "green peas", quantity: "2 tbsp" },
      { name: "onion", quantity: "1 small" },
      { name: "green chilli", quantity: "1" },
      { name: "butter", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/4 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Finely chop the carrot, bell pepper and onion.",
      "Melt the butter and saute the onion and green chilli for 1 minute.",
      "Add the carrot, bell pepper and peas, and stir-fry for 3 minutes.",
      "Add 1.5 cups of water and bring to a boil.",
      "Add the noodles, masala seasoning and turmeric, and cook for 2-3 minutes.",
      "Stir well and serve hot with a squeeze of lime."
    ],
    thumbnail: "",
    youtube: "https://www.youtube.com/watch?v=Hc_F6OHMpRU",
    sourceUrl: "",
    nutrition: { calories: 330, protein: 9, carbohydrates: 50, fat: 10, fiber: 3, sugar: 4, sodium: 1050, estimated: true, perServing: true },
    cookingTime: 12,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Cheese Maggi",
    slug: "cheese-maggi",
    area: "Indian",
    isVeg: true,
    category: "Quick Meal",
    tags: ["indian", "maggi", "noodles", "cheese", "vegetarian", "quick", "comfort-food"],
    ingredients: [
      { name: "instant noodles", quantity: "2 packets" },
      { name: "cheese", quantity: "50 g" },
      { name: "milk", quantity: "100 ml" },
      { name: "butter", quantity: "1 tbsp" },
      { name: "onion", quantity: "1 small" },
      { name: "green chilli", quantity: "1" },
      { name: "black pepper", quantity: "1/4 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil 1 cup of water with the milk in a pan.",
      "Melt the butter and saute the onion and green chilli for 2 minutes.",
      "Add the noodle cakes and the masala seasoning, and cook for 2 minutes.",
      "When the noodles are nearly done, grate in the cheese and stir until melted and creamy.",
      "Finish with black pepper and adjust salt.",
      "Serve hot while the cheese is gooey."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Egg_noodles_with_Tadkedar_mac%26cheese.jpg/960px-Egg_noodles_with_Tadkedar_mac%26cheese.jpg",
    youtube: "https://www.youtube.com/watch?v=Hc_F6OHMpRU",
    sourceUrl: "",
    nutrition: { calories: 450, protein: 15, carbohydrates: 50, fat: 20, fiber: 2, sugar: 4, sodium: 1150, estimated: true, perServing: true },
    cookingTime: 12,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Egg Maggi",
    slug: "egg-maggi",
    area: "Indian",
    isVeg: false,
    category: "Quick Meal",
    tags: ["indian", "maggi", "noodles", "egg", "non-vegetarian", "quick", "high-protein"],
    ingredients: [
      { name: "instant noodles", quantity: "2 packets" },
      { name: "eggs", quantity: "2" },
      { name: "onion", quantity: "1 small" },
      { name: "green chilli", quantity: "1" },
      { name: "butter", quantity: "1 tbsp" },
      { name: "turmeric", quantity: "1/4 tsp" },
      { name: "black pepper", quantity: "1/4 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil 1.5 cups of water in a pan.",
      "Melt the butter and saute the onion and green chilli for 2 minutes.",
      "Crack in the eggs and scramble them lightly until just set, then remove from the pan.",
      "Add the water, noodles and masala seasoning, and cook for 2-3 minutes.",
      "Return the scrambled eggs to the pan and fold them in with turmeric and black pepper.",
      "Cook for 1 more minute and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Noodles_and_fried_egg_2.jpg",
    youtube: "https://www.youtube.com/watch?v=7q2XzirOcrw",
    sourceUrl: "",
    nutrition: { calories: 400, protein: 16, carbohydrates: 50, fat: 15, fiber: 2, sugar: 3, sodium: 1100, estimated: true, perServing: true },
    cookingTime: 12,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Vegetable Hakka Noodles",
    slug: "vegetable-hakka-noodles",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Noodles",
    tags: ["indo-chinese", "noodles", "vegetarian", "lunch", "wok", "stir-fry"],
    ingredients: [
      { name: "hakka noodles", quantity: "250 g" },
      { name: "cabbage", quantity: "100 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "green beans", quantity: "50 g" },
      { name: "onion", quantity: "1 small" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "chilli sauce", quantity: "1 tbsp" },
      { name: "spring onion", quantity: "2 stalks" }
    ],
    instructions: [
      "Boil the hakka noodles in salted water until al dente, drain, rinse and toss with a little oil.",
      "Julienne the cabbage, carrot, bell pepper and beans, and slice the onion and spring onion.",
      "Heat oil in a wok on high heat and add the chopped garlic and ginger.",
      "Add the onion and stir-fry for 30 seconds, then the beans and carrot for 1 minute.",
      "Add the cabbage and bell pepper, and stir-fry on high for 2 minutes, keeping them crunchy.",
      "Add the soy sauce, vinegar and chilli sauce, then the noodles.",
      "Toss everything on high heat for 2 minutes, garnish with spring onion and serve immediately."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Hakka_Noodles_Veg.jpg/960px-Hakka_Noodles_Veg.jpg",
    youtube: "https://www.youtube.com/watch?v=7kwmmK4FhCI",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 10, carbohydrates: 55, fat: 13, fiber: 4, sugar: 4, sodium: 950, estimated: true, perServing: true },
    cookingTime: 20,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Chicken Hakka Noodles",
    slug: "chicken-hakka-noodles",
    area: "Indo-Chinese",
    isVeg: false,
    category: "Noodles",
    tags: ["indo-chinese", "noodles", "chicken", "non-vegetarian", "lunch", "high-protein"],
    ingredients: [
      { name: "hakka noodles", quantity: "250 g" },
      { name: "chicken", quantity: "200 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "cabbage", quantity: "100 g" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "chilli sauce", quantity: "1 tbsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "oil", quantity: "2 tbsp" }
    ],
    instructions: [
      "Boil the hakka noodles until al dente, drain, rinse and toss with a little oil.",
      "Slice the chicken thinly and julienne the carrot, cabbage and bell pepper.",
      "Heat oil in a wok on high and sear the chicken slices for 4-5 minutes until cooked and lightly charred. Remove.",
      "Add garlic and ginger to the wok, then the vegetables, and stir-fry for 2 minutes on high.",
      "Return the chicken to the wok and add soy sauce, vinegar and chilli sauce.",
      "Add the noodles and toss on high heat for 2 minutes.",
      "Garnish with spring onion and serve hot."
    ],
    thumbnail: "",
    youtube: "https://www.youtube.com/watch?v=iyVM1_OcbZU",
    sourceUrl: "",
    nutrition: { calories: 420, protein: 22, carbohydrates: 55, fat: 13, fiber: 3, sugar: 4, sodium: 1000, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "medium",
    servings: 3
  },
  {
    name: "Schezwan Noodles",
    slug: "schezwan-noodles",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Noodles",
    tags: ["indo-chinese", "noodles", "spicy", "vegetarian", "lunch", "street-food"],
    ingredients: [
      { name: "hakka noodles", quantity: "250 g" },
      { name: "schezwan sauce", quantity: "3 tbsp" },
      { name: "carrot", quantity: "1 medium" },
      { name: "bell pepper", quantity: "1" },
      { name: "cabbage", quantity: "100 g" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "red chilli flakes", quantity: "1 tsp" },
      { name: "soy sauce", quantity: "1 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "oil", quantity: "2 tbsp" }
    ],
    instructions: [
      "Boil the hakka noodles until al dente, drain, rinse and toss with a little oil.",
      "Julienne the carrot, bell pepper and cabbage, and finely chop the garlic and ginger.",
      "Heat oil in a wok and fry the garlic, ginger and chilli flakes until fragrant.",
      "Add the vegetables and stir-fry on high heat for 2-3 minutes, keeping them crisp.",
      "Add the schezwan sauce and soy sauce, and stir for a minute.",
      "Add the noodles and vinegar, and toss on high heat for 2 minutes until well coated.",
      "Garnish with spring onion and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Schezwan_noodles.jpg/960px-Schezwan_noodles.jpg",
    youtube: "https://www.youtube.com/watch?v=UjZ12LmO_is",
    sourceUrl: "",
    nutrition: { calories: 400, protein: 10, carbohydrates: 58, fat: 14, fiber: 4, sugar: 5, sodium: 1200, estimated: true, perServing: true },
    cookingTime: 20,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Chilli Garlic Noodles",
    slug: "chilli-garlic-noodles",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Noodles",
    tags: ["indo-chinese", "noodles", "garlic", "spicy", "vegetarian", "quick"],
    ingredients: [
      { name: "hakka noodles", quantity: "250 g" },
      { name: "garlic", quantity: "6 cloves" },
      { name: "green chilli", quantity: "2" },
      { name: "carrot", quantity: "1 medium" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "cabbage", quantity: "100 g" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "chilli sauce", quantity: "1 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the hakka noodles until al dente, drain, rinse and toss with a little oil.",
      "Thinly slice the garlic and green chillies, and julienne the vegetables.",
      "Heat oil in a wok and fry the garlic and green chillies until the garlic is golden and crisp.",
      "Add the vegetables and stir-fry on high heat for 2-3 minutes.",
      "Add the soy sauce, chilli sauce and vinegar.",
      "Add the noodles and toss everything on high heat for 2 minutes.",
      "Garnish with spring onion and serve hot."
    ],
    thumbnail: "",
    youtube: "https://www.youtube.com/watch?v=HFUt5JOdHhI",
    sourceUrl: "",
    nutrition: { calories: 390, protein: 10, carbohydrates: 56, fat: 13, fiber: 3, sugar: 4, sodium: 1050, estimated: true, perServing: true },
    cookingTime: 20,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Veg Fried Rice",
    slug: "veg-fried-rice",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Rice",
    tags: ["indo-chinese", "fried-rice", "vegetarian", "rice", "quick", "wok"],
    ingredients: [
      { name: "basmati rice", quantity: "300 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "green beans", quantity: "60 g" },
      { name: "green peas", quantity: "60 g" },
      { name: "cabbage", quantity: "80 g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "sesame oil", quantity: "1 tsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "white pepper", quantity: "1/4 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Cook the rice a day ahead or at least 2 hours before, and refrigerate so the grains stay separate.",
      "Chop all the vegetables into small dice.",
      "Heat oil in a wok on high and add the chopped garlic.",
      "Add the carrot, beans, peas and cabbage, and stir-fry for 3 minutes.",
      "Push the vegetables aside and add the cold rice to the wok.",
      "Add the soy sauce, vinegar, sesame oil, white pepper and salt, and toss on high heat for 3 minutes.",
      "Stir in the spring onion and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Veg_fried_rice_-_1.jpg/960px-Veg_fried_rice_-_1.jpg",
    youtube: "https://www.youtube.com/watch?v=yz_it7Aq0P8",
    sourceUrl: "",
    nutrition: { calories: 340, protein: 8, carbohydrates: 52, fat: 11, fiber: 4, sugar: 3, sodium: 750, estimated: true, perServing: true },
    cookingTime: 20,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Chicken Fried Rice",
    slug: "chicken-fried-rice",
    area: "Indo-Chinese",
    isVeg: false,
    category: "Rice",
    tags: ["indo-chinese", "fried-rice", "chicken", "non-vegetarian", "rice", "high-protein"],
    ingredients: [
      { name: "basmati rice", quantity: "300 g" },
      { name: "chicken", quantity: "200 g" },
      { name: "carrot", quantity: "1 medium" },
      { name: "green peas", quantity: "60 g" },
      { name: "green beans", quantity: "60 g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "egg", quantity: "1" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Cook the rice in advance and chill it so the grains stay separate.",
      "Dice the chicken small and season with a pinch of salt.",
      "Heat oil in a wok and scramble the egg, then remove and set aside.",
      "Sear the chicken in the wok for 4-5 minutes until cooked, then remove.",
      "Add the garlic, carrot, beans and peas, and stir-fry for 3 minutes.",
      "Add the cold rice, soy sauce and vinegar, then return the chicken and egg.",
      "Toss on high heat for 3 minutes, season, garnish with spring onion and serve."
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/wuyd2h1765655837.jpg",
    youtube: "https://www.youtube.com/watch?v=mUr-7wjhHuU",
    sourceUrl: "https://www.simplyrecipes.com/recipes/chicken_fried_rice/",
    nutrition: { calories: 420, protein: 24, carbohydrates: 52, fat: 13, fiber: 3, sugar: 3, sodium: 850, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 4
  },
  {
    name: "Gobi Manchurian",
    slug: "gobi-manchurian",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Indo-Chinese",
    tags: ["indo-chinese", "cauliflower", "vegetarian", "snack", "street-food", "starter"],
    ingredients: [
      { name: "cauliflower", quantity: "1 medium" },
      { name: "cornflour", quantity: "3 tbsp" },
      { name: "all-purpose flour", quantity: "2 tbsp" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "soy sauce", quantity: "2 tbsp" },
      { name: "chilli sauce", quantity: "2 tbsp" },
      { name: "vinegar", quantity: "1 tbsp" },
      { name: "onion", quantity: "1 small" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "black pepper", quantity: "1/2 tsp" },
      { name: "oil", quantity: "for frying" }
    ],
    instructions: [
      "Cut the cauliflower into florets, wash and drain thoroughly.",
      "Make a thick batter of cornflour, all-purpose flour, ginger garlic paste, black pepper and water.",
      "Coat the florets in the batter and deep-fry until crisp and golden. Drain.",
      "Heat a little oil in a wok and saute the chopped onion and bell pepper for 2 minutes.",
      "Add the soy sauce, chilli sauce and vinegar, and a splash of water.",
      "Add the fried florets and toss on high heat until the sauce coats them.",
      "Garnish with spring onion and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Gobi_manchurian.jpg",
    youtube: "https://www.youtube.com/watch?v=SxqUj4zJVN4",
    sourceUrl: "",
    nutrition: { calories: 280, protein: 8, carbohydrates: 30, fat: 15, fiber: 5, sugar: 8, sodium: 950, estimated: true, perServing: true },
    cookingTime: 35,
    difficulty: "medium",
    servings: 3
  },
  {
    name: "Paneer Chilli",
    slug: "paneer-chilli",
    area: "Indo-Chinese",
    isVeg: true,
    category: "Indo-Chinese",
    tags: ["indo-chinese", "paneer", "vegetarian", "starter", "spicy", "high-protein"],
    ingredients: [
      { name: "paneer", quantity: "300 g" },
      { name: "cornflour", quantity: "3 tbsp" },
      { name: "bell pepper", quantity: "1" },
      { name: "onion", quantity: "1 medium" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "ginger", quantity: "1 inch" },
      { name: "soy sauce", quantity: "1 tbsp" },
      { name: "chilli sauce", quantity: "2 tbsp" },
      { name: "schezwan sauce", quantity: "1 tbsp" },
      { name: "vinegar", quantity: "1 tsp" },
      { name: "spring onion", quantity: "2 stalks" },
      { name: "oil", quantity: "for frying" }
    ],
    instructions: [
      "Cut the paneer into cubes and coat them lightly in cornflour.",
      "Deep-fry or pan-fry the paneer cubes until golden and crisp. Drain.",
      "Heat a little oil and saute the chopped garlic and ginger until fragrant.",
      "Add the onion and bell pepper chunks, and stir-fry on high heat for 2-3 minutes.",
      "Add the soy sauce, chilli sauce, schezwan sauce and vinegar, and stir for a minute.",
      "Add the fried paneer and toss until coated in the sauce.",
      "Garnish with spring onion and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Chilli_Paneer.JPG/960px-Chilli_Paneer.JPG",
    youtube: "https://www.youtube.com/watch?v=hzWDhbCLFVE",
    sourceUrl: "",
    nutrition: { calories: 330, protein: 16, carbohydrates: 18, fat: 22, fiber: 3, sugar: 6, sodium: 900, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "medium",
    servings: 3
  },
  {
    name: "Masala Pasta",
    slug: "masala-pasta",
    area: "Indian",
    isVeg: true,
    category: "Pasta",
    tags: ["indian", "pasta", "vegetarian", "quick", "fusion", "comfort-food"],
    ingredients: [
      { name: "pasta", quantity: "250 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "red chilli powder", quantity: "1/2 tsp" },
      { name: "tomato ketchup", quantity: "1 tbsp" },
      { name: "cheese", quantity: "30 g" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "coriander", quantity: "a handful" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the pasta in salted water until al dente, drain and toss with a little oil.",
      "Heat the oil and saute the chopped garlic and onion until soft.",
      "Add the chopped tomatoes and bell pepper, and cook until the tomatoes turn pulpy.",
      "Add the garam masala, red chilli powder, ketchup and salt, and cook for 2 minutes.",
      "Add the boiled pasta and toss until well coated in the masala.",
      "Grate the cheese over the top and toss once more.",
      "Garnish with coriander and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Pennette_with_Curry-Masala_sauce_%283405972805%29.jpg/960px-Pennette_with_Curry-Masala_sauce_%283405972805%29.jpg",
    youtube: "https://www.youtube.com/watch?v=vHT78HtptUY",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 12, carbohydrates: 55, fat: 13, fiber: 4, sugar: 5, sodium: 800, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Red Sauce Pasta",
    slug: "red-sauce-pasta",
    area: "Italian",
    isVeg: true,
    category: "Pasta",
    tags: ["italian", "pasta", "tomato", "vegetarian", "dinner", "vegetarian"],
    ingredients: [
      { name: "pasta", quantity: "250 g" },
      { name: "tomato", quantity: "4 medium" },
      { name: "onion", quantity: "1 medium" },
      { name: "garlic", quantity: "4 cloves" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "dried oregano", quantity: "1 tsp" },
      { name: "red chilli flakes", quantity: "1/2 tsp" },
      { name: "cheese", quantity: "30 g" },
      { name: "basil", quantity: "a few leaves" },
      { name: "sugar", quantity: "1/2 tsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the pasta in salted water until al dente, reserve a cup of pasta water and drain.",
      "Puree the tomatoes in a blender.",
      "Heat the olive oil and saute the chopped onion and garlic until soft.",
      "Add the tomato puree, sugar and salt, and simmer for 12-15 minutes until thickened.",
      "Stir in the oregano and red chilli flakes.",
      "Add the pasta and toss in the sauce, loosening with pasta water if needed.",
      "Garnish with basil and grated cheese and serve hot."
    ],
    thumbnail: "",
    youtube: "https://www.youtube.com/watch?v=XnGhDm2PCNA",
    sourceUrl: "",
    nutrition: { calories: 360, protein: 12, carbohydrates: 58, fat: 10, fiber: 5, sugar: 8, sodium: 650, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "White Sauce Pasta",
    slug: "white-sauce-pasta",
    area: "Italian",
    isVeg: true,
    category: "Pasta",
    tags: ["italian", "pasta", "creamy", "vegetarian", "dinner", "comfort-food"],
    ingredients: [
      { name: "pasta", quantity: "250 g" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "all-purpose flour", quantity: "2 tbsp" },
      { name: "milk", quantity: "500 ml" },
      { name: "cheese", quantity: "50 g" },
      { name: "garlic", quantity: "3 cloves" },
      { name: "black pepper", quantity: "1/2 tsp" },
      { name: "dried oregano", quantity: "1 tsp" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "sweet corn", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the pasta in salted water until al dente and drain.",
      "Melt the butter and saute the chopped garlic until fragrant.",
      "Add the flour and cook for a minute, stirring constantly.",
      "Gradually whisk in the milk and cook until the sauce thickens, about 5 minutes.",
      "Stir in the cheese, black pepper, oregano and salt.",
      "Add the chopped bell pepper and corn, and simmer for 3 minutes.",
      "Add the pasta, coat well in the sauce and serve hot."
    ],
    thumbnail: "",
    youtube: "https://www.youtube.com/watch?v=l_HOohJZL0U",
    sourceUrl: "",
    nutrition: { calories: 480, protein: 16, carbohydrates: 55, fat: 22, fiber: 4, sugar: 5, sodium: 750, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "medium",
    servings: 3
  },
  {
    name: "Arrabbiata Pasta",
    slug: "arrabbiata-pasta",
    area: "Italian",
    isVeg: true,
    category: "Pasta",
    tags: ["italian", "pasta", "spicy", "tomato", "vegetarian", "dinner"],
    ingredients: [
      { name: "pasta", quantity: "250 g" },
      { name: "tomato", quantity: "5 medium" },
      { name: "garlic", quantity: "5 cloves" },
      { name: "red chilli flakes", quantity: "1 tsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "basil", quantity: "a few leaves" },
      { name: "parsley", quantity: "1 tbsp" },
      { name: "cheese", quantity: "30 g" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the pasta in salted water until al dente, reserve a little pasta water and drain.",
      "Chop the tomatoes finely or puree them roughly.",
      "Heat the olive oil and fry the sliced garlic and red chilli flakes until fragrant.",
      "Add the tomatoes and salt, and simmer for 12-15 minutes until the sauce thickens.",
      "Tear in the basil leaves and cook for a minute.",
      "Add the pasta and toss with a splash of pasta water to coat.",
      "Finish with parsley and grated cheese and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Vegan_gnocchi_arrabbiata.jpg/960px-Vegan_gnocchi_arrabbiata.jpg",
    youtube: "https://www.youtube.com/watch?v=YJ3_l6mIV60",
    sourceUrl: "",
    nutrition: { calories: 350, protein: 12, carbohydrates: 56, fat: 10, fiber: 5, sugar: 7, sodium: 700, estimated: true, perServing: true },
    cookingTime: 30,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Indian-Style Macaroni",
    slug: "indian-style-macaroni",
    area: "Indian",
    isVeg: true,
    category: "Pasta",
    tags: ["indian", "macaroni", "pasta", "vegetarian", "lunch", "comfort-food"],
    ingredients: [
      { name: "macaroni", quantity: "250 g" },
      { name: "onion", quantity: "1 medium" },
      { name: "tomato", quantity: "2 medium" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "carrot", quantity: "1/2 medium" },
      { name: "green peas", quantity: "2 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "tomato ketchup", quantity: "1 tbsp" },
      { name: "cheese", quantity: "30 g" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the macaroni in salted water until al dente and drain.",
      "Heat the oil and saute the chopped onion until soft.",
      "Add the chopped tomatoes, carrot and bell pepper, and cook for 4 minutes.",
      "Add the green peas, turmeric, garam masala, ketchup and salt, and cook for 3 minutes.",
      "Add the boiled macaroni and toss until well mixed.",
      "Grate the cheese over the top and toss once.",
      "Serve hot with a side of ketchup."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Masala_Macroni.jpg/960px-Masala_Macroni.jpg",
    youtube: "https://www.youtube.com/watch?v=r79HcXZ_41o",
    sourceUrl: "",
    nutrition: { calories: 390, protein: 12, carbohydrates: 56, fat: 14, fiber: 4, sugar: 6, sodium: 850, estimated: true, perServing: true },
    cookingTime: 25,
    difficulty: "easy",
    servings: 3
  },
  {
    name: "Vegetable Sandwich",
    slug: "vegetable-sandwich",
    area: "Indian",
    isVeg: true,
    category: "Breakfast",
    tags: ["indian", "sandwich", "vegetarian", "breakfast", "quick", "snack"],
    ingredients: [
      { name: "bread", quantity: "8 slices" },
      { name: "cucumber", quantity: "1/2" },
      { name: "tomato", quantity: "1 medium" },
      { name: "onion", quantity: "1 small" },
      { name: "potato", quantity: "1 medium" },
      { name: "green chutney", quantity: "3 tbsp" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "chaat masala", quantity: "1/2 tsp" },
      { name: "salt", quantity: "to taste" },
      { name: "coriander", quantity: "a handful" }
    ],
    instructions: [
      "Boil the potato, then slice it into thin rounds.",
      "Slice the cucumber, tomato and onion into thin rounds.",
      "Spread butter and a layer of green chutney on the bread slices.",
      "Layer the potato, cucumber, tomato and onion on one slice.",
      "Sprinkle chaat masala, salt and chopped coriander over the vegetables.",
      "Top with the second bread slice and press gently.",
      "Toast in a sandwich press or on a pan until golden on both sides, then slice diagonally and serve."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Vegetable_Sandwich_2.jpg/960px-Vegetable_Sandwich_2.jpg",
    youtube: "https://www.youtube.com/watch?v=hr-nrGnc5yk",
    sourceUrl: "",
    nutrition: { calories: 300, protein: 9, carbohydrates: 45, fat: 10, fiber: 6, sugar: 6, sodium: 700, estimated: true, perServing: true },
    cookingTime: 15,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Masala Dosa",
    slug: "masala-dosa",
    area: "Indian",
    isVeg: true,
    category: "Breakfast",
    tags: ["indian", "dosa", "south-indian", "vegetarian", "breakfast", "fermented"],
    ingredients: [
      { name: "dosa batter", quantity: "500 g" },
      { name: "potato", quantity: "3 medium" },
      { name: "onion", quantity: "1 medium" },
      { name: "mustard seeds", quantity: "1 tsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "curry leaves", quantity: "8 leaves" },
      { name: "green chilli", quantity: "2" },
      { name: "ginger", quantity: "1 inch" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil, peel and mash the potatoes coarsely.",
      "Heat ghee in a pan and crackle the mustard seeds and curry leaves.",
      "Add the chopped onion, green chillies and grated ginger, and saute until soft.",
      "Add the turmeric and salt, then the mashed potatoes, and stir well. Keep the masala warm.",
      "Heat a flat pan and pour a ladle of dosa batter in the centre, spreading it into a thin circle.",
      "Drizzle a little ghee around the edges and cook until golden and crisp.",
      "Place a spoonful of potato masala in the centre, fold the dosa over it and serve with chutney and sambar."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Masala_Dosa_02.jpg/960px-Masala_Dosa_02.jpg",
    youtube: "https://www.youtube.com/watch?v=J75VQSxOtdo",
    sourceUrl: "",
    nutrition: { calories: 350, protein: 8, carbohydrates: 55, fat: 11, fiber: 6, sugar: 4, sodium: 750, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 2
  },
  {
    name: "Paneer Paratha",
    slug: "paneer-paratha",
    area: "Indian",
    isVeg: true,
    category: "Breakfast",
    tags: ["indian", "paratha", "paneer", "vegetarian", "breakfast", "high-protein"],
    ingredients: [
      { name: "whole wheat flour", quantity: "300 g" },
      { name: "paneer", quantity: "200 g" },
      { name: "onion", quantity: "1 small" },
      { name: "green chilli", quantity: "2" },
      { name: "coriander", quantity: "a handful" },
      { name: "ajwain", quantity: "1/2 tsp" },
      { name: "cumin", quantity: "1/2 tsp" },
      { name: "ghee", quantity: "3 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Knead the whole wheat flour with water and a pinch of salt into a soft dough. Rest for 15 minutes.",
      "Mash the paneer and mix with chopped onion, green chillies, coriander, ajwain, cumin and salt.",
      "Divide the dough and filling into equal balls.",
      "Stuff each dough ball with a portion of the paneer filling and seal it shut.",
      "Roll each stuffed ball into a round paratha with a rolling pin.",
      "Cook the paratha on a hot griddle with ghee until golden spots appear on both sides.",
      "Serve hot with curd and pickle."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Paneer_paratha.jpeg/960px-Paneer_paratha.jpeg",
    youtube: "https://www.youtube.com/watch?v=mS8uOQh-ue8",
    sourceUrl: "",
    nutrition: { calories: 420, protein: 14, carbohydrates: 48, fat: 19, fiber: 4, sugar: 3, sodium: 700, estimated: true, perServing: true },
    cookingTime: 35,
    difficulty: "medium",
    servings: 2
  },
  {
    name: "Aloo Paratha",
    slug: "aloo-paratha",
    area: "Indian",
    isVeg: true,
    category: "Breakfast",
    tags: ["indian", "paratha", "potato", "vegetarian", "breakfast", "comfort-food"],
    ingredients: [
      { name: "whole wheat flour", quantity: "300 g" },
      { name: "potato", quantity: "3 medium" },
      { name: "cumin", quantity: "1/2 tsp" },
      { name: "green chilli", quantity: "2" },
      { name: "ginger", quantity: "1 inch" },
      { name: "coriander", quantity: "a handful" },
      { name: "ajwain", quantity: "1/2 tsp" },
      { name: "ghee", quantity: "3 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the potatoes, peel and mash them well.",
      "Mix in the cumin, ajwain, chopped green chillies, grated ginger, coriander and salt.",
      "Knead the whole wheat flour with water into a soft dough and rest for 15 minutes.",
      "Divide the dough and the potato filling into equal balls.",
      "Stuff each dough ball with filling, seal and roll into a paratha.",
      "Cook on a hot griddle with ghee until golden on both sides.",
      "Serve hot with curd and butter."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Aloo_Parantha.JPG/960px-Aloo_Parantha.JPG",
    youtube: "https://www.youtube.com/watch?v=dBXiHx11niM",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 8, carbohydrates: 55, fat: 14, fiber: 5, sugar: 3, sodium: 650, estimated: true, perServing: true },
    cookingTime: 35,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Poha",
    slug: "poha",
    area: "Indian",
    isVeg: true,
    category: "Breakfast",
    tags: ["indian", "poha", "flattened-rice", "vegetarian", "breakfast", "gluten-free"],
    ingredients: [
      { name: "poha", quantity: "200 g" },
      { name: "onion", quantity: "1 small" },
      { name: "potato", quantity: "1 medium" },
      { name: "peanuts", quantity: "2 tbsp" },
      { name: "turmeric", quantity: "1/2 tsp" },
      { name: "green chilli", quantity: "2" },
      { name: "curry leaves", quantity: "8 leaves" },
      { name: "mustard seeds", quantity: "1 tsp" },
      { name: "lemon juice", quantity: "1 tbsp" },
      { name: "sugar", quantity: "1 tsp" },
      { name: "oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Rinse the poha in water and drain. Sprinkle a little salt and turmeric over it and let it sit while you prep the rest.",
      "Heat the oil and crackle the mustard seeds and curry leaves.",
      "Add the peanuts and fry until they turn crisp.",
      "Add the chopped onion, potato and green chillies, and cook until the potato is tender.",
      "Add the turmeric and remaining salt, and toss.",
      "Add the soaked poha and sugar, and stir gently for 3-4 minutes on low heat.",
      "Drizzle with lemon juice, garnish with coriander and serve hot."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Kande_pohe.jpg/960px-Kande_pohe.jpg",
    youtube: "https://www.youtube.com/watch?v=-ttCDDBXX4I",
    sourceUrl: "",
    nutrition: { calories: 280, protein: 6, carbohydrates: 45, fat: 8, fiber: 3, sugar: 4, sodium: 550, estimated: true, perServing: true },
    cookingTime: 15,
    difficulty: "easy",
    servings: 2
  },
  {
    name: "Samosa",
    slug: "samosa",
    area: "Indian",
    isVeg: true,
    category: "Street Food",
    tags: ["indian", "samosa", "street-food", "vegetarian", "snack", "fried"],
    ingredients: [
      { name: "all-purpose flour", quantity: "300 g" },
      { name: "potato", quantity: "4 medium" },
      { name: "green peas", quantity: "100 g" },
      { name: "cumin", quantity: "1 tsp" },
      { name: "coriander powder", quantity: "1 tsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "green chilli", quantity: "2" },
      { name: "ginger", quantity: "1 inch" },
      { name: "ajwain", quantity: "1/2 tsp" },
      { name: "oil", quantity: "for frying" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Knead the flour with the ajwain, salt, 2 tbsp of oil and water into a stiff dough. Rest for 30 minutes.",
      "Boil and mash the potatoes, and boil the peas until soft.",
      "Heat a little oil, add the cumin, chopped green chillies and grated ginger.",
      "Add the peas, mashed potato, coriander powder, garam masala and salt, and cook for 3 minutes. Cool the filling.",
      "Divide the dough into balls and roll each into a thin circle, then cut in half.",
      "Form each half into a cone, fill with the potato mixture and seal the edges with water.",
      "Deep-fry the samosas on medium heat until golden and crisp. Serve with chutney."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Samosa-Indian-popular-snack.jpg/960px-Samosa-Indian-popular-snack.jpg",
    youtube: "https://www.youtube.com/watch?v=cN7paRwBbrY",
    sourceUrl: "",
    nutrition: { calories: 250, protein: 4, carbohydrates: 28, fat: 13, fiber: 2, sugar: 2, sodium: 400, estimated: true, perServing: true },
    cookingTime: 50,
    difficulty: "medium",
    servings: 4
  },
  {
    name: "Pav Bhaji",
    slug: "pav-bhaji",
    area: "Indian",
    isVeg: true,
    category: "Street Food",
    tags: ["indian", "pav-bhaji", "street-food", "vegetarian", "dinner", "mumbai"],
    ingredients: [
      { name: "pav", quantity: "8 buns" },
      { name: "potato", quantity: "3 medium" },
      { name: "cauliflower", quantity: "100 g" },
      { name: "green peas", quantity: "100 g" },
      { name: "bell pepper", quantity: "1/2" },
      { name: "tomato", quantity: "3 medium" },
      { name: "onion", quantity: "1 large" },
      { name: "ginger garlic paste", quantity: "1 tbsp" },
      { name: "pav bhaji masala", quantity: "2 tbsp" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "lemon juice", quantity: "1 tbsp" },
      { name: "salt", quantity: "to taste" }
    ],
    instructions: [
      "Boil the potatoes, cauliflower and peas until soft, then mash them together.",
      "Heat the butter and saute the chopped onion until soft and pink.",
      "Add the ginger garlic paste and cook for a minute.",
      "Add the chopped tomatoes and bell pepper, and cook until the tomatoes turn pulpy.",
      "Add the pav bhaji masala and salt, and cook for 2 minutes.",
      "Add the mashed vegetables and 1 cup of water, and simmer for 10-12 minutes, mashing everything together.",
      "Toast the pav buns in butter, top with chopped onion, lemon juice and a pat of butter, and serve with the bhaji."
    ],
    thumbnail: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Pav_Bhaji_Homemade.jpg/960px-Pav_Bhaji_Homemade.jpg",
    youtube: "https://www.youtube.com/watch?v=qMAYG-soxhw",
    sourceUrl: "",
    nutrition: { calories: 380, protein: 9, carbohydrates: 55, fat: 14, fiber: 8, sugar: 7, sodium: 850, estimated: true, perServing: true },
    cookingTime: 40,
    difficulty: "medium",
    servings: 4
  }
];
